### ISSUE TITLE
Brainstorm TODO's

### ISSUE THREAD

**Issue by MaryImarenezor** [MaryImarenezor/milestone-project-1#1]
- [x] update documentation hub

- [x] review documentation and see which ones are the best to use

- [x] watch yt videos on them if necessary
